apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: roundrobin
  labels:
    consumes: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      provides: roundrobin
  template:
    metadata:
      labels:
        provides: roundrobin
    spec:
      containers:
      - name: roundrobin
        imagePullPolicy: Never # I'm too lazy to set up a registry for my minikube setup
        image: roundrobin:1
